// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Domain.Stepper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildList")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisplayNodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DisplayPercentForParentNode")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsChildNode")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsSubNode")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVisited")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NodeStepNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeStepNumberHTMLElement")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeTextHTMLElement")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Steppers");
                });
#pragma warning restore 612, 618
        }
    }
}
